stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
      - data_ingestion.py
    outs:
      - data/raw

  
  data_preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data/raw
      - data_preprocessing.py
    outs:
      - data/processed

  
  feature_engineering:
    cmd: python feature_engineering.py
    deps:
      - data/processed
      - feature_engineering.py
    outs:
      - data/features


  model_building:
    cmd: python model_building.py
    deps:
      - data/features
      - model_building.py
    outs:
      - model.pkl


  
  model_evaluation:
    cmd: python model_evaluation.py
    deps:
        - model.pkl
        - model_evaluation.py
    metrics:
        - metrics.json